openapi: 3.0.1
info:
  title: API Voto Electronico
  description: API Rest, consejo superior.<h1> Controles de cambio <hr>01-07-2022
  version: 2.0.0
servers:
- url: https://test.com:20320/api/firma-electronica
paths:
  /:
 
    get:
      tags:
      - Consultar-firma-electronica
      summary: Consultar firma-electronica por id firma-electronica
      description: firma-electronica
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/firma-electronica-consulta'
        500:
          description: Error de servidor/servicio inactivo, validar con soporte.
          content: {}
    post:
      tags:
      - Crear-firma-electronica.
      summary: firma-electronica
      description: firma-electronica
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/firma-electronica-rq'
        required: false
      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/firma-electronica-rs'
        404:
          $ref: '#/components/schemas/firma-electronica-generica'
      x-codegen-request-body-name: crear-firma-electronica
      
      
    put:
      tags:
      - Actualizar-firma-electronica
      summary: firma-electronica
      description: firma-electronica
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/firma-electronica-rq'
        required: false
      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/firma-electronica-rs'
        404:
          $ref: '#/components/schemas/firma-electronica-generica'
      x-codegen-request-body-name: actualizar-firma-electronica

    delete:
      tags:
      - Eliminar-firma-electronica
      summary: firma-electronica
      description: firma-electronica

      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/firma-electronica-rs'
        404:
          $ref: '#/components/schemas/firma-electronica-generica'
      x-codegen-request-body-name: actualizar-firma-electronica
  
#------------------------------------------------------------------------------------  
components:
  schemas:
  
 
            
    firma-electronica-rq:
      type: object
      properties:
        id:
          maxLength: 50
          type: string
          description: id
        estado:
          maxLength: 50
          type: string
          description: Estado del proceso
        owner:
          maxLength: 50
          type: string
          description: Fecha y hora de actualizaci贸n
        procesoDinamico:
          maxLength: 50
          type: string
          description: Votantes
        documentoOriginal:
          maxLength: 50
          type: string
          description: Estado de votantes
        plazo:
          maxLength: 50
          type: string
          description: Numero de rondas de votaci贸n

        estaticos:
          exclusiveMinimum: true
          type: array
          description: campos estaticos
          items:
            type: object
            properties:
              numeroFirmantes:
                type: string
                description: numero de firmantes
              firmantes:
                exclusiveMinimum: true
                type: array
                description: firmantes
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                      description: nombre
                    firma:
                      type: string
                      description: firma
        dinamicos:
          exclusiveMinimum: true
          type: array
          description: campos dinamicos
          items:
            type: object
            properties:
              cierreDocumento:
                type: boolean
                description: cierre de documento     
            
        firmaUsuario:
          maxLength: 50
          type: string
          description: Firma usuario
        fechaHoraFirma:
          maxLength: 50
          type: string
          description: Fecha y hora de firma
 
          



#------------------------------------------------------------------------------------ 
    

    
    
    firma-electronica-rs:
      type: object
      properties:
            codigo:
              type: string
            mensaje:
              type: string
               
               
    firma-electronica-consulta:
      type: object
      properties:
            codigo:
              type: string
            mensaje:
              type: string
            contenido:
              type: object
              properties:
               
                  id:
                    maxLength: 50
                    type: string
                    description: id
                  estado:
                    maxLength: 50
                    type: string
                    description: Estado del proceso
                  owner:
                    maxLength: 50
                    type: string
                    description: Fecha y hora de actualizaci贸n
                  procesoDinamico:
                    maxLength: 50
                    type: string
                    description: Votantes
                  documentoOriginal:
                    maxLength: 50
                    type: string
                    description: Estado de votantes
                  plazo:
                    maxLength: 50
                    type: string
                    description: Numero de rondas de votaci贸n
          
                  estaticos:
                    exclusiveMinimum: true
                    type: array
                    description: campos estaticos
                    items:
                      type: object
                      properties:
                        numeroFirmantes:
                          type: string
                          description: numero de firmantes
                        firmantes:
                          exclusiveMinimum: true
                          type: array
                          description: firmantes
                          items:
                            type: object
                            properties:
                              nombre:
                                type: string
                                description: nombre
                              firma:
                                type: string
                                description: firma
                  dinamicos:
                    exclusiveMinimum: true
                    type: array
                    description: campos dinamicos
                    items:
                      type: object
                      properties:
                        cierreDocumento:
                          type: boolean
                          description: cierre de documento     
                      
                  firmaUsuario:
                    maxLength: 50
                    type: string
                    description: Firma usuario
                  fechaHoraFirma:
                    maxLength: 50
                    type: string
                    description: Fecha y hora de firma
                        
    firma-electronica-generica:
      type: object
      properties:
            codigo:
              type: string
            mensaje:
              type: string
            error:
               type: string
              
    

