openapi: 3.0.1
info:
  title: API proceso-reparto
  description: API Rest, consejo superior.<h1> Controles de cambio <hr>21-03-2022
  version: 2.0.0
servers:
- url: https://test.com:20320/api/reparto/proceso
paths:
  /:
 
    get:
      tags:
      - Consultar-proceso
      summary: Consultar proceso por id proceso
      description: This operation is to know if the service is active
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/proceso-reparto-consulta'
        500:
          description: Error de servidor/servicio inactivo, validar con soporte.
          content: {}
    post:
      tags:
      - Crear-proceso.
      summary: proceso-reparto
      description: proceso-reparto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/proceso-reparto-rq'
        required: false
      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/proceso-reparto-rs'
        404:
          $ref: '#/components/schemas/proceso-reparto-generica'
      x-codegen-request-body-name: crear-proceso
      
      
    put:
      tags:
      - Actualizar-proceso
      summary: proceso-reparto
      description: proceso-reparto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/proceso-reparto-rq'
        required: false
      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/proceso-reparto-rs'
        404:
          $ref: '#/components/schemas/proceso-reparto-generica'
      x-codegen-request-body-name: actualizar-proceso

    delete:
      tags:
      - Eliminar-proceso
      summary: proceso-reparto
      description: proceso-reparto

      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/proceso-reparto-rs'
        404:
          $ref: '#/components/schemas/proceso-reparto-generica'
      x-codegen-request-body-name: actualizar-proceso
  
#------------------------------------------------------------------------------------  
components:
  schemas:
  
 
            
    proceso-reparto-rq:
      type: object
      properties:
        id:
          maxLength: 50
          type: string
          description: id
        tipo:
          maxLength: 50
          type: string
          description: tipo
        estado:
          maxLength: 50
          type: string
          description: estado
        owner:
          maxLength: 50
          type: string
          description: owner
        codigo:
          maxLength: 50
          type: string
          description: codigo
        accion:
          maxLength: 50
          type: string
          description: accion
        juridiccion:
          maxLength: 50
          type: string
          description: juridicion
        despacho:
          maxLength: 50
          type: string
          description: despacho
        demandante:
          maxLength: 50
          type: string
          description: demandante
        demandado:
          maxLength: 50
          type: string
          description: demandado
        firmantes:
          exclusiveMinimum: true
          type: array
          description: firmantes del proceso
          items:
            type: object
            properties:
              firmante:
                type: string
                description: nombre del firmante
              firma:
                type: string
                description: has de la firma
        resultadosMotor:
          exclusiveMinimum: true
          type: array
          description: datos del contacto
          items:
            type: object
            properties:
              llave:
                type: string
                description: id
              valor:
                type: string
                description: id
        documentosAsociados:
          exclusiveMinimum: true
          type: array
          description: has documentos asociacion
          items:
            type: string
          



#------------------------------------------------------------------------------------ 
    

    
    
    proceso-reparto-rs:
      type: object
      properties:
            codigo:
              type: string
            mensaje:
              type: string
               
               
    proceso-reparto-consulta:
      type: object
      properties:
            codigo:
              type: string
            mensaje:
              type: string
            contenido:
              type: object
              properties:
                id:
                  maxLength: 50
                  type: string
                  description: id
                tipo:
                  maxLength: 50
                  type: string
                  description: tipo
                estado:
                  maxLength: 50
                  type: string
                  description: estado
                owner:
                  maxLength: 50
                  type: string
                  description: owner
                codigo:
                  maxLength: 50
                  type: string
                  description: codigo
                accion:
                  maxLength: 50
                  type: string
                  description: accion
                juridiccion:
                  maxLength: 50
                  type: string
                  description: juridicion
                despacho:
                  maxLength: 50
                  type: string
                  description: despacho
                demandante:
                  maxLength: 50
                  type: string
                  description: demandante
                demandado:
                  maxLength: 50
                  type: string
                  description: demandado
                firmantes:
                  exclusiveMinimum: true
                  type: array
                  description: firmantes del proceso
                  items:
                    type: object
                    properties:
                      firmante:
                        type: string
                        description: nombre del firmante
                      firma:
                        type: string
                        description: has de la firma
                resultadosMotor:
                  exclusiveMinimum: true
                  type: array
                  description: datos del contacto
                  items:
                    type: object
                    properties:
                      llave:
                        type: string
                        description: id
                      valor:
                        type: string
                        description: id
                documentosAsociados:
                  exclusiveMinimum: true
                  type: array
                  description: has documentos asociacion
                  items:
                    type: string
                        
    proceso-reparto-generica:
      type: object
      properties:
            codigo:
              type: string
            mensaje:
              type: string
            error:
               type: string
              
    

